---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: 'test/data_bags'
  environments_path: 'test/environments'
  client_rb:
    environment: 'kitchen'
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[simple_patcher::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
